version: "3.2"
services:
  wartimer:
    container_name: wartimer
    image: wartimer:latest
    restart: unless-stopped
    environment:
      - DISCORD_CLIENT_TOKEN=<token>
      - DISCORD_CLIENT_ID=<id>
      - OWNER_ID<id> # Optional: The owner can interact with the bot on any server without requiring editor or assistant roles
      - TZ=Europe/Berlin # Determines the timezone of scheduled raidhelper events
  mongo:
    image: mongo:4.4.18
    restart: always
    volumes:
      - <localpath>:/data/db